version: "3.8"

services:
  app:
    platform: linux/arm64
    build:
      context: .
    env_file: .env # Основной источник переменных
    environment:
      - DB_HOST=db # Явно указываем имя сервиса
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_NAME=flight-connector
    ports:
      - "3202:3202"
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  db:
    platform: linux/arm64
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres # Явно указываем значения
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: flight-connector
    ports:
      - "5433:5432" # Внешний:5433, внутренний:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d flight-connector"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
