services:
  test-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: flight-connector-test
    ports:
      - "5434:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d flight-connector-test"]
      interval: 5s
      timeout: 3s
      retries: 5
  test-redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - test_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
  test-runner:
    build: .
    environment:
      NODE_ENV: test
      DB_HOST: test-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: flight-connector-test
    depends_on:
      test-db:
        condition: service_healthy
      test-redis:
        condition: service_healthy
volumes:
  test_postgres_data:
  test_redis_data:
